spring:
  datasource:
    url: jdbc:mysql://localhost:3306/getmyfood_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyThatIs32charsOrMore}
  expiration: 3600000 # 1 hour in ms